services:
  wg-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: iiixor/wg-micro-api:latest # Замени iiixor на свой Docker Hub username
    container_name: wg-micro-api
    env_file:
      - .env
    ports:
      - "8080:8080"
    # volumes: # Секция volumes полностью удалена для wg0.conf и логов, так как wg0.conf копируется в образ, а логи в stdout
    restart: unless-stopped
    # network_mode: host # Оставляем для тестирования, потом можно попробовать убрать
    cap_add:
      - NET_ADMIN
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -q --spider --tries=1 --timeout=10 http://localhost:8080/healthz || exit 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
