services:
  wg-api:
    build: .
    image: iiixor/wg-api:latest
    env_file:
      - .env # <- подгружает все переменные из этого файла[2]
    ports:
      - "8080:8080"
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
