basePath: /
definitions:
  domain.AllowedIpsUpdate:
    properties:
      allowedIps:
        example:
        - 10.0.0.2/32
        items:
          type: string
        type: array
    type: object
  domain.Config:
    properties:
      allowedIps:
        description: AllowedIps – список разрешённых IP/Netmask для этого peer’а
        items:
          type: string
        type: array
      endpoint:
        description: Endpoint – адрес (IP:port) к которому peer коннектится
        type: string
      latestHandshake:
        description: LatestHandshake – время последнего рукопожатия в UNIX-секундах
        type: integer
      persistentKeepalive:
        description: PersistentKeepalive – интервал keepalive в секундах (0 или off)
        type: integer
      preSharedKey:
        description: PreSharedKey – опциональный pre-shared ключ
        type: string
      privateKey:
        type: string
      publicKey:
        description: PublicKey – публичный ключ peer’а
        type: string
      receiveBytes:
        description: ReceiveBytes – сколько байт получено
        type: integer
      transmitBytes:
        description: TransmitBytes – сколько байт передано
        type: integer
    type: object
  domain.ErrorResponse:
    properties:
      error:
        example: Peer не найден
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Управление настройками WireGuard через HTTP
  title: WireGuard API Service
  version: "1.0"
paths:
  /configs:
    get:
      description: Возвращает список всех peer-конфигураций
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Config'
            type: array
        "400":
          description: bad request
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "500":
          description: internal error
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
      summary: List all peer configurations
      tags:
      - configs
    post:
      consumes:
      - application/json
      description: Создает новую конфигурацию для peer-а, используя publicKey и список
        разрешенных IP
      parameters:
      - description: Данные новой конфигурации
        in: body
        name: config
        required: true
        schema:
          $ref: '#/definitions/domain.Config'
      produces:
      - application/json
      responses:
        "201":
          description: создано успешно
          schema:
            type: string
        "400":
          description: неверный формат запроса
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "500":
          description: ошибка создания конфигурации
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
      summary: Create a new peer configuration
      tags:
      - configs
  /configs/{publicKey}:
    delete:
      description: Полностью удаляет конфигурацию peer-а по публичному ключу
      parameters:
      - description: Public key peer'а
        in: path
        name: publicKey
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: удалено успешно
          schema:
            type: string
        "404":
          description: peer не найден
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "500":
          description: ошибка удаления
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
      summary: Delete a peer configuration
      tags:
      - configs
    get:
      description: Возвращает информацию об одной конфигурации WireGuard по публичному
        ключу
      parameters:
      - description: Public key peer'а
        in: path
        name: publicKey
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Config'
        "404":
          description: конфигурация не найдена
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "500":
          description: внутренняя ошибка
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
      summary: Get configuration by public key
      tags:
      - configs
  /configs/{publicKey}/allowed-ips:
    put:
      consumes:
      - application/json
      description: Заменяет список разрешенных IP-адресов для указанного peer-а
      parameters:
      - description: Public key peer'а
        in: path
        name: publicKey
        required: true
        type: string
      - description: Список разрешенных IP-адресов
        in: body
        name: allowedIps
        required: true
        schema:
          $ref: '#/definitions/domain.AllowedIpsUpdate'
      produces:
      - application/json
      responses:
        "200":
          description: обновлено успешно
          schema:
            type: string
        "400":
          description: неверный формат запроса
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "404":
          description: peer не найден
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "500":
          description: ошибка обновления
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
      summary: Update allowed IPs for a peer
      tags:
      - configs
  /configs/{publicKey}/file:
    get:
      description: Генерирует и скачивает файл конфигурации .conf для peer-а по publicKey
      parameters:
      - description: Public key peer'а
        in: path
        name: publicKey
        required: true
        type: string
      produces:
      - text/plain
      responses:
        "200":
          description: WireGuard .conf файл
          schema:
            type: file
        "404":
          description: конфигурация не найдена
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "500":
          description: ошибка создания файла конфигурации
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
      summary: Export WireGuard config file
      tags:
      - configs
swagger: "2.0"
