basePath: /
definitions:
  domain.AllowedIpsUpdate:
    properties:
      allowedIps:
        example:
        - 10.0.0.2/32
        items:
          type: string
        type: array
    type: object
  domain.Config:
    properties:
      allowedIps:
        description: AllowedIps – список разрешённых IP/Netmask для этого peer’а
        items:
          type: string
        type: array
      endpoint:
        description: Endpoint – адрес (IP:port) к которому peer коннектится
        type: string
      latestHandshake:
        description: LatestHandshake – время последнего рукопожатия в UNIX-секундах
        type: integer
      persistentKeepalive:
        description: PersistentKeepalive – интервал keepalive в секундах (0 или off)
        type: integer
      preSharedKey:
        description: PreSharedKey – опциональный pre-shared ключ
        type: string
      privateKey:
        type: string
      publicKey:
        description: PublicKey – публичный ключ peer’а
        type: string
      receiveBytes:
        description: ReceiveBytes – сколько байт получено
        type: integer
      transmitBytes:
        description: TransmitBytes – сколько байт передано
        type: integer
    type: object
  domain.ErrorResponse:
    properties:
      error:
        example: Peer не найден
        type: string
    type: object
  domain.HealthResponse:
    properties:
      status:
        example: ok
        type: string
    type: object
  domain.ReadinessResponse:
    properties:
      error:
        example: wg command failed
        type: string
      status:
        example: ready
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Управление настройками WireGuard через HTTP
  title: WireGuard API Service
  version: "1.0"
paths:
  /configs:
    get:
      description: Возвращает список всех peer-конфигураций
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Config'
            type: array
        "500":
          description: internal error
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "503":
          description: WireGuard недоступен
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
      summary: List all peer configurations
      tags:
      - configs
    post:
      consumes:
      - application/json
      description: Создаёт новую конфигурацию для peer-а
      parameters:
      - description: New configuration
        in: body
        name: config
        required: true
        schema:
          $ref: '#/definitions/domain.Config'
      produces:
      - application/json
      responses:
        "201":
          description: created
          schema:
            type: string
        "400":
          description: invalid input
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "500":
          description: internal error
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "503":
          description: WireGuard недоступен
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
      summary: Create new peer configuration
      tags:
      - configs
  /configs/{publicKey}:
    delete:
      description: Удаляет конфигурацию peer-а по публичному ключу
      parameters:
      - description: Public key peer'а
        in: path
        name: publicKey
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: deleted
          schema:
            type: string
        "500":
          description: internal error
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "503":
          description: WireGuard недоступен
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
      summary: Delete a peer configuration
      tags:
      - configs
    get:
      description: Возвращает информацию по публичному ключу
      parameters:
      - description: Public key peer'а
        in: path
        name: publicKey
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Config'
        "404":
          description: config not found
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "503":
          description: WireGuard недоступен
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
      summary: Get configuration by public key
      tags:
      - configs
  /configs/{publicKey}/allowed-ips:
    put:
      consumes:
      - application/json
      description: Заменяет список разрешённых IP-адресов
      parameters:
      - description: Public key peer'а
        in: path
        name: publicKey
        required: true
        type: string
      - description: New allowed IPs
        in: body
        name: allowedIps
        required: true
        schema:
          $ref: '#/definitions/domain.AllowedIpsUpdate'
      produces:
      - application/json
      responses:
        "200":
          description: updated
          schema:
            type: string
        "400":
          description: invalid input
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "500":
          description: internal error
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "503":
          description: WireGuard недоступен
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
      summary: Update allowed IPs for a peer
      tags:
      - configs
  /configs/{publicKey}/file:
    get:
      description: Генерирует и возвращает .conf-файл для клиента
      parameters:
      - description: Public key peer'а
        in: path
        name: publicKey
        required: true
        type: string
      produces:
      - text/plain
      responses:
        "200":
          description: WireGuard .conf file
          schema:
            type: file
        "404":
          description: config not found
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "503":
          description: WireGuard недоступен
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
      summary: Export WireGuard config file
      tags:
      - configs
  /configs/{publicKey}/rotate:
    post:
      description: Удаляет пир по publicKey и создаёт нового с теми же AllowedIps
      parameters:
      - description: Old public key
        in: path
        name: publicKey
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: новая конфигурация
          schema:
            $ref: '#/definitions/domain.Config'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
      summary: Rotate peer key
      tags:
      - configs
  /healthz:
    get:
      description: Простая проверка, что сервис запущен
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.HealthResponse'
      summary: Liveness probe
      tags:
      - health
  /readyz:
    get:
      description: Проверка, что сервис может обращаться к утилите wg
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.ReadinessResponse'
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/domain.ReadinessResponse'
      summary: Readiness probe
      tags:
      - health
swagger: "2.0"
